image: alpine/edge
packages: [ zola ]
oauth: pages.sr.ht/PAGES:RW
environment:
  site: www.rekayasawan.com
sources:
  - https://git.sr.ht/~rekayasawan/website
tasks:
  - build: |
      cd website
      zola build
  - package: |
      cd website
      tar -C public -cvz . > ../site.tar.gz
  - upload: |
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz