# The URL the site will be built for
base_url = "https://rekayasawan.pages.dev"
theme = "lightspeed"
title = "Rekayasawan"
description = "blog nya rekayasawan perangkat lunak"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feed = true

highlight_code = true
highlight_theme = "gruvbox-light"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "base16-ocean-dark"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true


[extra]
# Put all your custom variables here
seo = true
author = "azul"
ogimage = "lightning.png"

zola = false
netlify = false
maintained_with_love = false

footer_links = [
    {url = "$BASE_URL/", name = "Beranda"},
    {url = "$BASE_URL/tentang", name = "Tentang"},
    {url = "$BASE_URL/atom.xml", name = "RSS"},
    {url = "https://github.com/azulkipli/rekayasawan", name = "Kode di Github"},
]
